name: deploy-pipeline
on:
    push:
        branches: ["master"]
jobs:
    cancel-workflows:
        runs-on: ubuntu-latest
        steps:
            - name: Cancel Workflow Action
              uses: styfle/cancel-workflow-action@0.11.0
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: set JDK
              uses: actions/setup-java@v3
              with:
                distribution: 'eclipse-temurin'
                java-version: '20.0.1'
            - name: cdk diff
              uses: parameswaranvv/aws-java-cdk-github-actions@v1
              with:
                cdk_subcommand: 'diff'
                actions_comment: true
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: 'us-east-1'
            - name: cdk deploy
              uses: parameswaranvv/aws-java-cdk-github-actions@v1
              with:
                cdk_subcommand: 'deploy'
                cdk_stack: 'stack1'
                cdk_args: '--require-approval never'
                actions_comment: false
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: 'us-east-1'
            
            

        

